services:
  hhplus-mysql:
    image: mysql:8.0
    container_name: hhplus-mysql
    restart: unless-stopped
    environment:
      LANGUAGE: ko_KR.UTF-8
      LANG: ko_KR.UTF-8
      MYSQL_ROOT_PASSWORD: 'root1234!'
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'UTC'
    ports:
      - '3306:3306'
    volumes:
      - ./infra/initdb:/docker-entrypoint-initdb.d
      # - hhplus_mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --authentication-policy=caching_sha2_password
      - --host-cache-size=0

  # Redis (통합: 세션, 캐시, 분산락, NoSQL)
  hhplus-redis:
    image: redis:8.4.0
    restart: unless-stopped
    container_name: hhplus-redis
    ports:
      - '6379:6379'
    command: redis-server --maxmemory 512mb --maxmemory-policy noeviction

  # Redis Seed (쿠폰 등 초기 데이터)
  hhplus-redis-seed:
    image: redis:8.4.0
    restart: 'no'
    container_name: hhplus-redis-seed
    depends_on:
      - hhplus-redis
    environment:
      REDIS_HOST: hhplus-redis
      REDIS_PORT: 6379
    volumes:
      - ./infra/initredis/seed-coupons.sh:/seed/seed-coupons.sh:ro
    entrypoint:
      [
        '/bin/sh',
        '-c',
        'tr -d "\\r" < /seed/seed-coupons.sh > /tmp/seed.sh && sh /tmp/seed.sh',
      ]

  # Kafka Cluster (1 node for development)
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093

      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:9094,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      # 단일 노드용 설정
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    volumes:
      - kafka_data:/tmp/kraft-combined-logs

  ## ========== Kafka Web UI ==========
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - '8080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
volumes:
  kafka_data:
  # hhplus_mysql_data:
